version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Teste.ListaTarefa.WebApi/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./AppData:/app/AppData
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./AppData:/data

  e2etests:
    image: ${DOCKER_REGISTRY-}e2etests
    build:
      context: .
      dockerfile: Teste.ListaTarefa.E2ETest/Dockerfile
    depends_on:
      - api
