services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Teste.ListaTarefa.WebApi/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./AppData:/app/AppData
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./AppData:/data
